[project]
name = "bduq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "icecream>=2.1.7",
    "python-dotenv>=1.1.1",
]
